config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'about/contacts'
  get 'about/analytics'
  get 'about/health_and_safety'
  resources :about

  get 'homepage/index'

  resources :articles do
    resources :article_comments
  end

  resources :blogs do
    resources :blog_comments
  end

  resources :blog_views

  resources :recipes do
    resources :recipe_comments
  end

  resources :visitors

  root 'homepage#index'

  get 'their_recipes/acorn_squash_caramelized_onion_goat_cheese_pizza'
  get 'their_recipes/asparagus_avocado_sushi'
  get 'their_recipes/bacon_egg_and_spinach_fried_rice'
  get 'their_recipes/bacon_herb_and_cheese_star_bread'
  get 'their_recipes/baked_potatoes'
  get 'their_recipes/baked_scotch_eggs'
  get 'their_recipes/beef_stew_in_red_wine_sauce'
  get 'their_recipes/beef_stew_with_dumplings'
  get 'their_recipes/beef_tenderloin_steaks_with_celert_root_gratin'
  get 'their_recipes/bibimbap'
  get 'their_recipes/blueberry_vanilla_cake'
  get 'their_recipes/bouillabaisse'
  get 'their_recipes/braised_lamb_with_herb_scented_jus'
  get 'their_recipes/caramel_cookies'
  get 'their_recipes/caramelised_onions'
  get 'their_recipes/cassoulet_with_duck_confit'
  get 'their_recipes/chicken_pesto_pene_with_bacon_and_feta'
  get 'their_recipes/cheese_and_ham_omelette'
  get 'their_recipes/chicken_noodle_soup'
  get 'their_recipes/chocolate_cake'
  get 'their_recipes/chocolate_macarons'
  get 'their_recipes/cream_cheese_and_jalapeno_stuffed_chicken_breast'
  get 'their_recipes/creamy_scallop_fettuccine_with_lemon_and_capers'
  get 'their_recipes/creamy_tomato_soup'
  get 'their_recipes/devonshire_honey_cake'
  get 'their_recipes/dinner_rolls'
  get 'their_recipes/firecracker_shrimp'
  get 'their_recipes/fruit_clafoutis'
  get 'their_recipes/garlic_butter_steak_and_potatoes'
  get 'their_recipes/grilled_chicken_salad_with_cabbage'
  get 'their_recipes/grilled_oysters'
  get 'their_recipes/honey_and_mustard_roast_gammon'
  get 'their_recipes/honey_mustard_chicken_thighs_with_argula'
  get 'their_recipes/honey_tamarind_baby_back_ribs'
  get 'their_recipes/hunters_sausage_and_sauerkraut_stew'
  get 'their_recipes/injera'
  get 'their_recipes/lembas_bread'
  get 'their_recipes/lemon_pie'
  get 'their_recipes/mars_bar_cake'
  get 'their_recipes/marshmallow_crispie_bars'
  get 'their_recipes/moroccan_braised_chicken'
  get 'their_recipes/mussels_and_clams_in_a_spicy_tomato_broth'
  get 'their_recipes/over_the_top_mushroom_quiche'
  get 'their_recipes/paella'
  get 'their_recipes/pan_roast_salmon_with_tomato_viniagrette'
  get 'their_recipes/pancakes'
  get 'their_recipes/parmesan_and_garlic_crusted_potato_wedges'
  get 'their_recipes/potato_gnocchi_with_mushroom_ragu'
  get 'their_recipes/potato_wedges'
  get 'their_recipes/pull_apart_flauta_ring'
  get 'their_recipes/roast_chicken_with_aromatic_jus'
  get 'their_recipes/roast_leg_of_lamb'
  get 'their_recipes/russian_honey_cake'
  get 'their_recipes/samoa_cookie_inspired_iced_coffee'
  get 'their_recipes/seared_scallops_in_a_cream_lemon_caper_sauce'
  get 'their_recipes/slow_roasted_pork_loin_with_molasses_and_balsamic_glaze'
  get 'their_recipes/spicy_italian_pizza'
  get 'their_recipes/spinache_and_artichoke_dip_stuffed_garlic_bread'
  get 'their_recipes/trout_with_garlic_lemon_butter_herb_sauce'
  get 'their_recipes/welsh_rarebit'
  get 'their_recipes/template'
  get 'their_recipes/pasta_dishes'
  get 'their_recipes/potato_dishes'
  get 'their_recipes/seasonal'
  get 'their_recipes/drinks'
  get 'their_recipes/baking'
  get 'their_recipes/healthy'
  get 'their_recipes/easy'
  get 'their_recipes/asian'
  resources :their_recipes
end

app/models/about.rb
# frozen_string_literal: true

class About < ActiveRecord::Base
  has_many :general_page_views
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_many :article_comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5, maximum: 50 }
  validates :text, presence: true,
                   length: { minimum: 5, maximum: 5000 }
end

app/models/article_comment.rb
# frozen_string_literal: true

class ArticleComment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true,
                        length: { minimum: 5, maximum: 50 }
  validates :body, presence: true,
                   length: { minimum: 5, maximum: 255 }
end

app/models/article_view.rb
# frozen_string_literal: true

class ArticleView < ApplicationRecord
  attr_accessor :UserId, :PageId, :PageName

  def self.to_csv
    attributes = %w[id user_id page_id created_at updated_at page_name]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |articles_top10|
        csv << attributes.map { |attr| articles_top10.send(attr) }
      end
    end
  end
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  has_many :blog_comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5, maximum: 50 }
  validates :text, presence: true,
                   length: { minimum: 5, maximum: 5000 }
end

app/models/blog_comment.rb
# frozen_string_literal: true

class BlogComment < ApplicationRecord
  belongs_to :blog
  validates :commenter, presence: true,
                        length: { minimum: 5, maximum: 50 }
  validates :body, presence: true,
                   length: { minimum: 5, maximum: 255 }
end

app/models/blog_view.rb
# frozen_string_literal: true

class BlogView < ActiveRecord::Base
  attr_accessor :UserId, :PageId, :PageName

  def self.to_csv
    attributes = %w[id user_id page_id created_at updated_at page_name]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |blogs_top10|
        csv << attributes.map { |attr| blogs_top10.send(attr) }
      end
    end
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :article
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  has_many :recipe_comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5, maximum: 50 }
  validates :author, presence: true,
                     length: { minimum: 5, maximum: 50 }
  validates :ingredient, presence: true,
                         length: { minimum: 5, maximum: 5000 }
  validates :method, presence: true,
                     length: { minimum: 5, maximum: 5000 }
end

app/models/recipe_comment.rb
# frozen_string_literal: true

class RecipeComment < ApplicationRecord
  belongs_to :recipe
  validates :commenter, presence: true,
                        length: { minimum: 5, maximum: 50 }
  validates :body, presence: true,
                   length: { minimum: 5, maximum: 255 }
end

app/models/recipes_view.rb
# frozen_string_literal: true

class RecipesView < ApplicationRecord
  attr_accessor :UserId, :PageId, :PageName

  def self.to_csv
    attributes = %w[id user_id page_id page_name created_at updated_at]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |their_recipes_top10|
        csv << attributes.map { |attr| their_recipes_top10.send(attr) }
      end
    end
  end
end

app/models/theirrecipe.rb
# frozen_string_literal: true

class Theirrecipe < ApplicationRecord
  has_many :liked_theirrecipes
  has_many :visitors, through: :liked_theirrecipes
end

app/models/visitor.rb
# frozen_string_literal: true

require './lib/recommendation.rb'
class Visitor < ApplicationRecord
  attr_accessor :Name

  has_many :liked_theirrecipes
  has_many :theirrecipes, through: :liked_theirrecipes
  include Recommendation
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

class HomepageController < ApplicationController
  def index
    session_id = session.id
    GeneralPageService.record_visitors(session_id)
    GeneralPageService.record_views(session_id, 'Homepage')
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

module AboutHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/blogs_helper.rb
# frozen_string_literal: true

module BlogsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/legal_helper.rb
module LegalHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/homepage/index.html.erb
<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>

    <div class="slideshow_container">
      <div class="mySlides fade">
        <%= link_to their_recipes_blueberry_vanilla_cake_path do %>
          <img src="<%= asset_path('blueberry_vanilla_cake-wide.png') %>">
          <div class="text">
            <h2>
              Blueberries! Blueberries! Blueberries!
            </h2>
            <p>
              How does a no-bake (perfect for when you does't have an oven!)
              blueberry vanillia cake topped with blueberrys sound?
            </p>
          </div>
        <% end %>
      </div>

      <div class="mySlides fade">
        <%= link_to their_recipes_asparagus_avocado_sushi_path do %>
          <img src="<%= asset_path('asparagus_avocado_sushi-wide.png') %>">
          <div class="text">
            <h2>
              Asparagus and Avocado Sushi
            </h2>
            <p>
              A delicious dish for vegan sushi lovers, mixing Japanese
              cooking with your favourite veg and fruit
            </p>
          </div>
        <% end %>
      </div>

      <div class="mySlides fade">
        <%= link_to their_recipes_lembas_bread_path do %>
          <img src="<%= asset_path('lembas_bread_wide.png') %>">
          <div class="text">
            <h2>
              Lembas Bread
            </h2>
            <p>
              "is enough to fill the stomach of a grown man" - Legolas Greenleaf
              Try elven lembas bread! Elven made, hobbit tested
            </p>
          </div>
        <% end %>
      </div>

      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>

      <div class="bottom_menu">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
      </div>
    </div>

    <div class="clearfix">
      <div class='img-container'>

      </div>
      <%= link_to their_recipes_pasta_dishes_path do %>
        <div class="img-container">
          <%= image_tag('pasta_dishes.png', :alt => 'Pasta Dishes') %>
          <h2>Pasta Dishes</h2>
          <p>
            Carb load while unleashing your inner Italian
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_potato_dishes_path do %>
        <div class="img-container">
          <%= image_tag('potato_dishes.png', :alt => 'Potato Dishes') %>
          <h2>Potato Dishes</h2>
          <p>
            Boil them, mash them, stick them in a stew
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_seasonal_path do %>
        <div class="img-container">
          <%= image_tag('seasonal.png', :alt => 'Seasonal') %>
          <h2>Seasonal</h2>
          <p>
            It says seasonal but we really mean Christmas now
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_drinks_path do %>
        <div class="img-container">
          <%= image_tag('drinks.png', :alt => 'Drinks') %>
          <h2>Drinks</h2>
          <p>
            Whooooo! Cocktails and smoothies all round
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_baking_path do %>
        <div class="img-container">
          <%= image_tag('baking.png', :alt => 'Baking') %>
          <h2>Baking</h2>
          <p>
            Cakes, pies, doughnuts, etc.
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_healthy_path do %>
        <div class="img-container">
          <%= image_tag('healthy.png', :alt => 'Healthy') %>
          <h2>Healthy</h2>
          <p>
            Green, green, and more greens!
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_easy_path do %>
        <div class="img-container">
          <%= image_tag('easy.png', :alt => 'Quick and Easy') %>
          <h2>Quick and Easy</h2>
          <p>
            (Student compatible)
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_asian_path do %>
        <div class="img-container">
          <%= image_tag('asia.png', :alt => 'Asian') %>
          <h2>Asian</h2>
          <p>
            Everything! As long as that's Indian, Chinese, Korean and Japanese...
          </p>
        </div>
      <% end %>
    </div>

  </div>
</div>
<%= render 'shared/footer' %>


<script>
  var slideIndex = 1;
  showSlides(slideIndex);

  // Next/previous controls
  function plusSlides(n) {
    showSlides(slideIndex += n);
  }

  // Thumbnail image controls
  function currentSlide(n) {
    showSlides(slideIndex = n);
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    if (n > slides.length) {slideIndex = 1}
    if (n < 1) {slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
  }
</script>