config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'about/contacts'
  get 'about/analytics'
  get 'about/health_and_safety'
  resources :about

  get 'homepage/index'

  resources :articles do
    resources :article_comments
  end

  resources :blogs do
    resources :blog_comments
  end

  resources :blog_views

  resources :recipes do
    resources :recipe_comments
  end

  resources :visitors

  root 'homepage#index'

  get 'their_recipes/acorn_squash_caramelized_onion_goat_cheese_pizza'
  get 'their_recipes/asparagus_avocado_sushi'
  get 'their_recipes/bacon_egg_and_spinach_fried_rice'
  get 'their_recipes/bacon_herb_and_cheese_star_bread'
  get 'their_recipes/baked_potatoes'
  get 'their_recipes/baked_scotch_eggs'
  get 'their_recipes/beef_stew_in_red_wine_sauce'
  get 'their_recipes/beef_stew_with_dumplings'
  get 'their_recipes/beef_tenderloin_steaks_with_celert_root_gratin'
  get 'their_recipes/bibimbap'
  get 'their_recipes/blueberry_vanilla_cake'
  get 'their_recipes/bouillabaisse'
  get 'their_recipes/braised_lamb_with_herb_scented_jus'
  get 'their_recipes/caramel_cookies'
  get 'their_recipes/caramelised_onions'
  get 'their_recipes/cassoulet_with_duck_confit'
  get 'their_recipes/chicken_pesto_pene_with_bacon_and_feta'
  get 'their_recipes/cheese_and_ham_omelette'
  get 'their_recipes/chicken_noodle_soup'
  get 'their_recipes/chocolate_cake'
  get 'their_recipes/chocolate_macarons'
  get 'their_recipes/cream_cheese_and_jalapeno_stuffed_chicken_breast'
  get 'their_recipes/creamy_scallop_fettuccine_with_lemon_and_capers'
  get 'their_recipes/creamy_tomato_soup'
  get 'their_recipes/devonshire_honey_cake'
  get 'their_recipes/dinner_rolls'
  get 'their_recipes/firecracker_shrimp'
  get 'their_recipes/fruit_clafoutis'
  get 'their_recipes/garlic_butter_steak_and_potatoes'
  get 'their_recipes/grilled_chicken_salad_with_cabbage'
  get 'their_recipes/grilled_oysters'
  get 'their_recipes/honey_and_mustard_roast_gammon'
  get 'their_recipes/honey_mustard_chicken_thighs_with_argula'
  get 'their_recipes/honey_tamarind_baby_back_ribs'
  get 'their_recipes/hunters_sausage_and_sauerkraut_stew'
  get 'their_recipes/injera'
  get 'their_recipes/lembas_bread'
  get 'their_recipes/lemon_pie'
  get 'their_recipes/mars_bar_cake'
  get 'their_recipes/marshmallow_crispie_bars'
  get 'their_recipes/moroccan_braised_chicken'
  get 'their_recipes/mussels_and_clams_in_a_spicy_tomato_broth'
  get 'their_recipes/over_the_top_mushroom_quiche'
  get 'their_recipes/paella'
  get 'their_recipes/pan_roast_salmon_with_tomato_viniagrette'
  get 'their_recipes/pancakes'
  get 'their_recipes/parmesan_and_garlic_crusted_potato_wedges'
  get 'their_recipes/potato_gnocchi_with_mushroom_ragu'
  get 'their_recipes/potato_wedges'
  get 'their_recipes/pull_apart_flauta_ring'
  get 'their_recipes/roast_chicken_with_aromatic_jus'
  get 'their_recipes/roast_leg_of_lamb'
  get 'their_recipes/russian_honey_cake'
  get 'their_recipes/samoa_cookie_inspired_iced_coffee'
  get 'their_recipes/seared_scallops_in_a_cream_lemon_caper_sauce'
  get 'their_recipes/slow_roasted_pork_loin_with_molasses_and_balsamic_glaze'
  get 'their_recipes/spicy_italian_pizza'
  get 'their_recipes/spinache_and_artichoke_dip_stuffed_garlic_bread'
  get 'their_recipes/trout_with_garlic_lemon_butter_herb_sauce'
  get 'their_recipes/welsh_rarebit'
  get 'their_recipes/template'
  get 'their_recipes/pasta_dishes'
  get 'their_recipes/potato_dishes'
  get 'their_recipes/seasonal'
  get 'their_recipes/drinks'
  get 'their_recipes/baking'
  get 'their_recipes/healthy'
  get 'their_recipes/easy'
  get 'their_recipes/asian'
  resources :their_recipes
end

app/models/their_recipes_view.rb
# frozen_string_literal: true

class TheirRecipesView < ApplicationRecord
  attr_accessor :UserId, :PageId, :PageName

  def self.to_csv
    attributes = %w[id user_id page_id page_name created_at updated_at]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |their_recipes_top10|
        csv << attributes.map { |attr| their_recipes_top10.send(attr) }
      end
    end
  end
end

app/models/theirrecipe.rb
# frozen_string_literal: true

class Theirrecipe < ApplicationRecord
  has_many :liked_theirrecipes
  has_many :visitors, through: :liked_theirrecipes
end

app/controllers/their_recipes_controller.rb
# frozen_string_literal: true

class TheirRecipesController < ApplicationController
  def index
    session_id = session.id
    GeneralPageService.record_views(session_id, 'Their Recipes')
  end

  def show; end

  def acorn_squash_caramelized_onion_goat_cheese_pizza
    TheirRecipesService.record_views(session.id, 1, 'Acorn squash caramelized onion goat cheese pizza')
  end

  def asparagus_avocado_sushi
    TheirRecipesService.record_views(session.id, 2, 'Asparagus avocado sushi')
  end

  def bacon_egg_and_spinach_fried_rice
    TheirRecipesService.record_views(session.id, 3, 'Bacon egg and spinach fried rice')
  end

  def bacon_herb_and_cheese_star_bread
    TheirRecipesService.record_views(session.id, 4, 'Bacon herb and cheese star bread')
  end

  def baked_potatoes
    TheirRecipesService.record_views(session.id, 5, 'Baked potatoes')
  end

  def baked_scotch_eggs
    TheirRecipesService.record_views(session.id, 6, 'Baked scotch eggs')
  end

  def beef_stew_in_red_wine_sauce
    TheirRecipesService.record_views(session.id, 7, 'Beef stew in red wine sauce')
  end

  def beef_stew_with_dumplings
    TheirRecipesService.record_views(session.id, 8, 'Beef stew with dumplings')
  end

  def beef_tenderloin_steaks_with_celert_root_gratin
    TheirRecipesService.record_views(session.id, 9, 'Beef tenderloin steaks with celert root gratin')
  end

  def bibimbap
    TheirRecipesService.record_views(session.id, 10, 'Bibimbap')
  end

  def blueberry_vanilla_cake
    TheirRecipesService.record_views(session.id, 11, 'Blueberry vanilla cake')
  end

  def bouillabaisse
    TheirRecipesService.record_views(session.id, 12, 'Bouillabaisse')
  end

  def braised_lamb_with_herb_scented_jus
    TheirRecipesService.record_views(session.id, 13, 'Braised lamb with herb scented jus')
  end

  def caramel_cookies
    TheirRecipesService.record_views(session.id, 14, 'Caramel cookies')
  end

  def caramelised_onions
    TheirRecipesService.record_views(session.id, 15, 'Caramelised onions')
  end

  def cassoulet_with_duck_confit
    TheirRecipesService.record_views(session.id, 16, 'Cassoulet with duck confit')
  end

  def chicken_pesto_pene_with_bacon_and_feta
    TheirRecipesService.record_views(session.id, 17, 'Chicken pesto pene with bacon and feta')
  end

  def cheese_and_ham_omelette
    TheirRecipesService.record_views(session.id, 18, 'Cheese and ham omelette')
  end

  def chicken_noodle_soup
    TheirRecipesService.record_views(session.id, 19, 'Chicken noodle soup')
  end

  def chocolate_cake
    TheirRecipesService.record_views(session.id, 20, 'Chocolate cake')
  end

  def chocolate_macarons
    TheirRecipesService.record_views(session.id, 21, 'Chocolate macarons')
  end

  def cream_cheese_and_jalapeno_stuffed_chicken_breast
    TheirRecipesService.record_views(session.id, 22, 'Cream cheese and jalapeno stuffed chicken breast')
  end

  def creamy_scallop_fettuccine_with_lemon_and_capers
    TheirRecipesService.record_views(session.id, 23, 'Creamy scallop fettuccine with lemon and capers')
  end

  def creamy_tomato_soup
    TheirRecipesService.record_views(session.id, 24, 'Creamy tomato soup')
  end

  def devonshire_honey_cake
    TheirRecipesService.record_views(session.id, 25, 'Devonshire honey cake')
  end

  def dinner_rolls
    TheirRecipesService.record_views(session.id, 26, 'Dinner rolls')
  end

  def firecracker_shrimp
    TheirRecipesService.record_views(session.id, 27, 'Firecracker shrimp')
  end

  def fruit_clafoutis
    TheirRecipesService.record_views(session.id, 28, 'Fruit clafoutis')
  end

  def garlic_butter_steak_and_potatoes
    TheirRecipesService.record_views(session.id, 29, 'Garlic butter steak and potatoes')
  end

  def grilled_chicken_salad_with_cabbage
    TheirRecipesService.record_views(session.id, 30, 'Grilled chicken salad with cabbage')
  end

  def grilled_oysters
    TheirRecipesService.record_views(session.id, 31, 'Grilled oysters')
  end

  def honey_and_mustard_roast_gammon
    TheirRecipesService.record_views(session.id, 32, 'Honey and mustard roast gammon')
  end

  def honey_mustard_chicken_thighs_with_argula
    TheirRecipesService.record_views(session.id, 33, 'Honey mustard chicken thighs with argula')
  end

  def honey_tamarind_baby_back_ribs
    TheirRecipesService.record_views(session.id, 34, 'Honey tamarind baby back ribs')
  end

  def hunters_sausage_and_sauerkraut_stew
    TheirRecipesService.record_views(session.id, 35, 'Hunters sausage and sauerkraut stew')
  end

  def injera
    TheirRecipesService.record_views(session.id, 36, 'Injera')
  end

  def lembas_bread
    TheirRecipesService.record_views(session.id, 37, 'Lembas bread')
  end

  def lemon_pie
    TheirRecipesService.record_views(session.id, 38, 'Lemon pie')
  end

  def mars_bar_cake
    TheirRecipesService.record_views(session.id, 39, 'Mars bar cake')
  end

  def marshmallow_crispie_bars
    TheirRecipesService.record_views(session.id, 40, 'Marshmallow crispie bars')
  end

  def moroccan_braised_chicken
    TheirRecipesService.record_views(session.id, 41, 'Moroccan braised chicken')
  end

  def mussels_and_clams_in_a_spicy_tomato_broth
    TheirRecipesService.record_views(session.id, 42, 'Mussels and clams in a spicy tomato broth')
  end

  def over_the_top_mushroom_quiche
    TheirRecipesService.record_views(session.id, 43, 'Over the top mushroom quiche')
  end

  def paella
    TheirRecipesService.record_views(session.id, 44, 'Paella')
  end

  def pan_roast_salmon_with_tomato_viniagrette
    TheirRecipesService.record_views(session.id, 45, 'Pan roast salmon with tomato viniagrette')
  end

  def pancakes
    TheirRecipesService.record_views(session.id, 46, 'Pancakes')
  end

  def parmesan_and_garlic_crusted_potato_wedges
    TheirRecipesService.record_views(session.id, 47, 'Parmesan and garlic crusted potato wedges')
  end

  def potato_gnocchi_with_mushroom_ragu
    TheirRecipesService.record_views(session.id, 48, 'Potato gnocchi with mushroom ragu')
  end

  def potato_wedges
    TheirRecipesService.record_views(session.id, 49, 'Potato wedges')
  end

  def pull_apart_flauta_ring
    TheirRecipesService.record_views(session.id, 50, 'Pull apart flauta ring')
  end

  def roast_chicken_with_aromatic_jus
    TheirRecipesService.record_views(session.id, 51, 'Roast chicken with aromatic jus')
  end

  def roast_leg_of_lamb
    TheirRecipesService.record_views(session.id, 52, 'Roast leg of lamb')
  end

  def russian_honey_cake
    TheirRecipesService.record_views(session.id, 53, 'Russian honey cake')
  end

  def samoa_cookie_inspired_iced_coffee
    TheirRecipesService.record_views(session.id, 54, 'Samoa cookie inspired iced coffee')
  end

  def seared_scallops_in_a_cream_lemon_caper_sauce
    TheirRecipesService.record_views(session.id, 55, 'Seared scallops in a cream lemon caper sauce')
  end

  def slow_roasted_pork_loin_with_molasses_and_balsamic_glaze
    TheirRecipesService.record_views(session.id, 56, 'Slow roasted pork loin with molasses and balsamic glaze')
  end

  def spicy_italian_pizza
    TheirRecipesService.record_views(session.id, 57, 'Spicy italian pizza')
  end

  def spinache_and_artichoke_dip_stuffed_garlic_bread
    TheirRecipesService.record_views(session.id, 58, 'Spinache and artichoke dip stuffed garlic bread')
  end

  def trout_with_garlic_lemon_butter_herb_sauce
    TheirRecipesService.record_views(session.id, 59, 'Trout with garlic lemon butter herb sauce')
  end

  def welsh_rarebit
    TheirRecipesService.record_views(session.id, 60, 'Welsh rarebit')
  end

  def asian; end

  def baking; end

  def drinks; end

  def easy; end

  def healthy; end

  def pasta_dishes; end

  def potato_dishes; end

  def seasonal; end
end

app/helpers/their_recipes_helper.rb
# frozen_string_literal: true

module TheirRecipesHelper
end

app/views/their_recipes/baked_scotch_eggs.html.erb
<link href='https://fonts.googleapis.com/css?family=Caveat Brush' rel='stylesheet'>

<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>
    <div class='picture'>

      <div class="polaroid">
        <%= image_tag('baked_scotch_eggs.png', :alt => 'Baked Scotch Eggs') %>
        <div class="polaroid_container">
          <p class='content_description'>
            Baked Scotch Eggs
          </p>
          <p>
            <%= link_to "Imgur User: WannaWanga - Family Recipes",
            "https://imgur.com/a/gqmNvIM",
            :target => "_blank" %>
          </p>
        </div>
      </div>

      <div class='description'>
        <ul>
          <li>
            <a>
              <h2>Description:</h2>
              <p>
                A popular UK recipe made slightly healthier by baking 
              </p>
              <p>
                Prep: 30 mins
                Cook: 35 mins
              </p>
            </a>
          </li>
        </ul>
      </div>

      <div class='ingredients'>
        <ul>
          <li>
            <a>
              <h2>Ingredients:</h2>
              <ul>
                <li> 1 lb bulk pork sausage </li>
                <li> 1 1 teaspoon salt dried minced onion </li>
                <li> 4 hard-cooked eggs </li>
                <li> All-purpose flour </li>
                <li> 3/4 cup crispy bread crumbs </li>
                <li> 1 egg, beaten  </li>
              </ul>
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class='method'>
      <div class='method_text'>
        <p>Method</p>
      </div>
      <div class='method_steps'>
        <ol>
          <p>
            Heat oven to 400°F. In large bowl, mix pork sausage, onion and salt.
            Shape mixture into 4 equal patties.
          </p>
          <p>
            Roll each hard-cooked egg in flour to coat; place on sausage patty
            and shape sausage around egg. Dip each into beaten egg; coat with
            bread crumbs to cover completely. Place on ungreased cookie sheet.
          </p>
          <p>
            Bake 35 minutes or until sausage is thoroughly cooked and no longer
            pink near egg.
          </p>
        </ol>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/their_recipes/beef_stew_with_dumplings.html.erb
<link href='https://fonts.googleapis.com/css?family=Caveat Brush' rel='stylesheet'>

<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>
    <div class='picture'>

      <div class="polaroid">
        <%= image_tag('beef_stew_with_dumplings.png', :alt => 'Beef Stew with Dumplings') %>
        <div class="polaroid_container">
          <p class='content_description'>
            Beef Stew with Dumplings
          </p>
          <p>
            <%= link_to "James Martin - BBC Food",
            "https://www.bbc.com/food/recipes/beefstewwithdumpling_87333",
            :target => "_blank" %>
          </p>
        </div>
      </div>

      <div class='description'>
        <ul>
          <li>
            <a>
              <h2>Description:</h2>
              <p>
                For the coldest wintry evenings, tuck into a rich beef stew with
                fluffy dumplings to warm you right down to your toes.
              </p>
              <p>
                Prep: 30 mins
                Cook: 2 hours
              </p>
            </a>
          </li>
        </ul>
      </div>

      <div class='ingredients'>
        <ul>
          <li>
            <a>
              <h2>Ingredients:</h2>
              <ul>
                <li> STEW </li>
                <li> 2 tbsp olive oil </li>
                <li> 25g/1oz butter </li>
                <li> 750g/1lb 10oz beef stewing steak, chopped into bite-sized pieces </li>
                <li> 2 tbsp plain flour </li>
                <li> 2 garlic cloves, crushed </li>
                <li> 175g/6oz baby onions, peeled </li>
                <li> 150g/5oz celery, cut into large chunks </li>
                <li> 150g/5oz carrots, cut into large chunks </li>
                <li> 2 leeks, roughly chopped </li>
                <li> 200g/7oz swede, cut into large chunks </li>
                <li> 150ml/5fl oz red wine </li>
                <li> 500ml/18fl oz beef stock </li>
                <li> 2 fresh bay leaves </li>
                <li> 3 tbsp fresh thyme leaves </li>
                <li> 3 tbsp chopped fresh flatleaf parsley </li>
                <li> Worcestershire sauce, to taste </li>
                <li> 1 tbsp balsamic vinegar, or to taste </li>
                <li> Salt and freshly ground black pepper </li>
                <li> DUMPLINGS </li>
                <li> 125g/4½oz plain flour, plus extra for dusting </li>
                <li> 1 tsp baking powder </li>
                <li> Pinch salt </li>
                <li> 60g/2½oz suet </li>
                <li> Water, to make a dough </li>
              </ul>
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class='method'>
      <div class='method_text'>
        <p>Method</p>
      </div>
      <div class='method_steps'>
        <ol>
          <p>
            Preheat the oven to 180C/350F/Gas 4.
          </p>
          <p>
            For the beef stew, heat the oil and butter in an ovenproof casserole
            and fry the beef until browned on all sides.
          </p>
          <p>
            Sprinkle over the flour and cook for a further 2-3 minutes.
          </p>
          <p>
            Add the garlic and all the vegetables and fry for 1-2 minutes.
          </p>
          <p>
            Stir in the wine, stock and herbs, then add the Worcestershire sauce
            and balsamic vinegar, to taste. Season with salt and freshly ground
            black pepper.
          </p>
          <p>
            Cover with a lid, transfer to the oven and cook for about two hours,
            or until the meat is tender.
          </p>
          <p>
            For the dumplings, sift the flour, baking powder and salt into a
            bowl.
          </p>
          <p>
            Add the suet and enough water to form a thick dough.
          </p>
          <p>
            With floured hands, roll spoonfuls of the dough into small balls.
          </p>
          <p>
            After two hours, remove the lid from the stew and place the balls on
            top of the stew. Cover, return to the oven and cook for a further
            20 minutes, or until the dumplings have swollen and are tender. (If
            you prefer your dumplings with a golden top, leave the lid off when
            returning to the oven.)
          </p>
          <p>
            To serve, place a spoonful of mashed potato onto each of four
            serving plates and top with the stew and dumplings. Sprinkle with
            chopped parsley.
          </p>
        </ol>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/their_recipes/chcken_pesto_pene_with_bacon_and_feta.html.erb
<link href='https://fonts.googleapis.com/css?family=Caveat Brush' rel='stylesheet'>

<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>
    <div class='picture'>

      <div class="polaroid">
        <%= image_tag('chcken_pesto_pene_with_bacon_and_feta.png', :alt => 'Chicken Pesto Penne With Bacon & Feta') %>
        <div class="polaroid_container">
          <p class='content_description'>
            Chicken Pesto Penne With Bacon & Feta
          </p>
          <p>
            <%= link_to "Reddit User: icingonthesteak - Reddit",
            "https://www.reddit.com/r/recipes/comments/9kelna/chicken_pesto_penne_with_bacon_feta/",
            :target => "_blank" %>
          </p>
        </div>
      </div>

      <div class='description'>
        <ul>
          <li>
            <a>
              <h2>Description:</h2>
              <p>
                A simple pasta dish for all to try
              </p>
              <p>
                Prep: 10 mins
                Cook: 15 mins
              </p>
            </a>
          </li>
        </ul>
      </div>

      <div class='ingredients'>
        <ul>
          <li>
            <a>
              <h2>Ingredients:</h2>
              <ul>
                <li> 300g Penne </li>
                <li> 1 tbsp Olive Oil </li>
                <li> 3 large Chicken Fillets breast fillets, cut into bite size pieces </li>
                <li> 4 Short Cut Bacon Rashers diced </li>
                <li> 100g Sun-Dried Tomatoes diced </li>
                <li> 1/2 cup Basil Pesto </li>
                <li> 60g Baby Spinach </li>
                <li> 1/3 cup Thickened Cream </li>
                <li> 100g Feta Crumbled </li>
              </ul>
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class='method'>
      <div class='method_text'>
        <p>Method</p>
      </div>
      <div class='method_steps'>
        <ol>
          <p>
            Cook penne according to packet instructions. Drain and set aside.
          </p>
          <p>
            Heat olive oil in a large frying pan over medium-high heat.
          </p>
          <p>
            Add chicken & bacon and cook until chicken is browned.
          </p>
          <p>
            Add sun-dried tomato, basil pesto & baby spinach and cook a further
            2 minutes or so until spinach is wilted. Stir to fully combine.
          </p>
          <p>
            Add thickened cream and cook a further 1-2 minutes to heat through.
          </p>
          <p>
            Add penne and toss to mix through and coat with the pesto sauce.
          </p>
          <p>
            Remove from heat, sprinkle with feta and serve.
          </p>
        </ol>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/their_recipes/healthy.html.erb
<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>
    <div class='preamble'>
      <h1>Healthy</h1>
      <p>
        Green, green, and more greens!
      </p>
    </div>

    <div class="clearfix">
      <%= link_to their_recipes_cheese_and_ham_omelette_path do %>
        <div class="nonFilterDiv healthy easy">
          <%= image_tag('cheese_and_ham_omelette.png', :alt => 'Cheese and Hame Omelette') %>
          <h2>Cheese and Hame Omelette</h2>
          <p>
            A classic omelette recipe, held together with strong cheese and
            mature ham
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_grilled_chicken_salad_with_cabbage_path do %>
        <div class="nonFilterDiv meat healthy">
          <%= image_tag('grilled_chicken_salad_with_cabbage.png', :alt => 'Grilled Chicken Salad with Cabbage and Raspberry Balsamic Dressing') %>
          <h2>Grilled Chicken Salad with Cabbage and Raspberry Balsamic Dressing</h2>
          <p>
            A marinated chicken, on a bed of salad, done with dressing
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_pan_roast_salmon_with_tomato_viniagrette_path do %>
        <div class="nonFilterDiv fish healthy">
          <%= image_tag('pan_roast_salmon_with_tomato_viniagrette.png', :alt => 'Pan-Roasted Salmon with Tomato Vinaigrette') %>
          <h2>Pan-Roasted Salmon with Tomato Vinaigrette</h2>
          <p>
            Seared salmon with an amazing sauce
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_potato_gnocchi_with_mushroom_ragu_path do %>
        <div class="nonFilterDiv potato_dishes healthy">
          <%= image_tag('potato_gnocchi_with_mushroom_ragu.png', :alt => 'Potato Gnocchi with Mushroom Ragù') %>
          <h2>Potato Gnocchi with Mushroom Ragù</h2>
          <p>
            Gnocchi and mushrooms what could go wrong
          </p>
        </div>
      <% end %>

    </div>

  </div>
</div>
<%= render 'shared/footer' %>

app/views/their_recipes/seasonal.html.erb
<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>
    <div class='preamble'>
      <h1>Seasonal</h1>
      <p>
        It says seasonal but we really mean Christmas now
      </p>
    </div>

    <div class="clearfix">
      <%= link_to their_recipes_braised_lamb_with_herb_scented_jus_path do %>
        <div class="nonFilterDiv meat roast seasonal">
          <%= image_tag('braised_lamb_with_herb_scented_jus.png', :alt => 'Braised Lamb with Herb-Scented Jus') %>
          <h2>Braised Lamb with Herb-Scented Jus</h2>
          <p>
            Tender braised leg of lamb to be served on a bed of vegtables
          </p>
        </div>
      <% end %>
      <%= link_to their_recipes_roast_leg_of_lamb_path do %>
        <div class="nonFilterDiv meat roast seasonal">
          <%= image_tag('roast_leg_of_lamb.png', :alt => 'Roast Leg of Lamb') %>
          <h2>Roast Leg of Lamb</h2>
          <p>
            The Greek way of doing a roast leg of lamb
          </p>
        </div>
      <% end %>
    </div>

  </div>
</div>
<%= render 'shared/footer' %>