config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'about/contacts'
  get 'about/analytics'
  get 'about/health_and_safety'
  resources :about

  get 'homepage/index'

  resources :articles do
    resources :article_comments
  end

  resources :blogs do
    resources :blog_comments
  end

  resources :blog_views

  resources :recipes do
    resources :recipe_comments
  end

  resources :visitors

  root 'homepage#index'

  get 'their_recipes/acorn_squash_caramelized_onion_goat_cheese_pizza'
  get 'their_recipes/asparagus_avocado_sushi'
  get 'their_recipes/bacon_egg_and_spinach_fried_rice'
  get 'their_recipes/bacon_herb_and_cheese_star_bread'
  get 'their_recipes/baked_potatoes'
  get 'their_recipes/baked_scotch_eggs'
  get 'their_recipes/beef_stew_in_red_wine_sauce'
  get 'their_recipes/beef_stew_with_dumplings'
  get 'their_recipes/beef_tenderloin_steaks_with_celert_root_gratin'
  get 'their_recipes/bibimbap'
  get 'their_recipes/blueberry_vanilla_cake'
  get 'their_recipes/bouillabaisse'
  get 'their_recipes/braised_lamb_with_herb_scented_jus'
  get 'their_recipes/caramel_cookies'
  get 'their_recipes/caramelised_onions'
  get 'their_recipes/cassoulet_with_duck_confit'
  get 'their_recipes/chicken_pesto_pene_with_bacon_and_feta'
  get 'their_recipes/cheese_and_ham_omelette'
  get 'their_recipes/chicken_noodle_soup'
  get 'their_recipes/chocolate_cake'
  get 'their_recipes/chocolate_macarons'
  get 'their_recipes/cream_cheese_and_jalapeno_stuffed_chicken_breast'
  get 'their_recipes/creamy_scallop_fettuccine_with_lemon_and_capers'
  get 'their_recipes/creamy_tomato_soup'
  get 'their_recipes/devonshire_honey_cake'
  get 'their_recipes/dinner_rolls'
  get 'their_recipes/firecracker_shrimp'
  get 'their_recipes/fruit_clafoutis'
  get 'their_recipes/garlic_butter_steak_and_potatoes'
  get 'their_recipes/grilled_chicken_salad_with_cabbage'
  get 'their_recipes/grilled_oysters'
  get 'their_recipes/honey_and_mustard_roast_gammon'
  get 'their_recipes/honey_mustard_chicken_thighs_with_argula'
  get 'their_recipes/honey_tamarind_baby_back_ribs'
  get 'their_recipes/hunters_sausage_and_sauerkraut_stew'
  get 'their_recipes/injera'
  get 'their_recipes/lembas_bread'
  get 'their_recipes/lemon_pie'
  get 'their_recipes/mars_bar_cake'
  get 'their_recipes/marshmallow_crispie_bars'
  get 'their_recipes/moroccan_braised_chicken'
  get 'their_recipes/mussels_and_clams_in_a_spicy_tomato_broth'
  get 'their_recipes/over_the_top_mushroom_quiche'
  get 'their_recipes/paella'
  get 'their_recipes/pan_roast_salmon_with_tomato_viniagrette'
  get 'their_recipes/pancakes'
  get 'their_recipes/parmesan_and_garlic_crusted_potato_wedges'
  get 'their_recipes/potato_gnocchi_with_mushroom_ragu'
  get 'their_recipes/potato_wedges'
  get 'their_recipes/pull_apart_flauta_ring'
  get 'their_recipes/roast_chicken_with_aromatic_jus'
  get 'their_recipes/roast_leg_of_lamb'
  get 'their_recipes/russian_honey_cake'
  get 'their_recipes/samoa_cookie_inspired_iced_coffee'
  get 'their_recipes/seared_scallops_in_a_cream_lemon_caper_sauce'
  get 'their_recipes/slow_roasted_pork_loin_with_molasses_and_balsamic_glaze'
  get 'their_recipes/spicy_italian_pizza'
  get 'their_recipes/spinache_and_artichoke_dip_stuffed_garlic_bread'
  get 'their_recipes/trout_with_garlic_lemon_butter_herb_sauce'
  get 'their_recipes/welsh_rarebit'
  get 'their_recipes/template'
  get 'their_recipes/pasta_dishes'
  get 'their_recipes/potato_dishes'
  get 'their_recipes/seasonal'
  get 'their_recipes/drinks'
  get 'their_recipes/baking'
  get 'their_recipes/healthy'
  get 'their_recipes/easy'
  get 'their_recipes/asian'
  resources :their_recipes
end

app/models/about.rb
# frozen_string_literal: true

class About < ActiveRecord::Base
  has_many :general_page_views
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index
    @abouts = AboutService.fetch_website_views
    @csv_type = params[:type]

    respond_to do |format|
      format.html
      format.csv do
        if @csv_type == '1'
          @website_hits = AboutService.fetch_website_views

          send_data @website_hits.to_csv,
                    filename: "WebsiteHits-#{Date.today}.csv"
        elsif @csv_type == '2'
          @blogs_top10 = AboutService.fetch_blog_views

          send_data @blogs_top10.to_csv,
                    filename: "Blogs-Top-10-#{Date.today}.csv"
        elsif @csv_type == '3'
          @recipes_top10 = AboutService.fetch_recipe_views

          send_data @recipes_top10.to_csv,
                    filename: "Recipes-Top-10-#{Date.today}.csv"
        elsif @csv_type == '4'
          @articles_top10 = AboutService.fetch_article_views

          send_data @articles_top10.to_csv,
                    filename: "Articles-Top-10-#{Date.today}.csv"
        elsif @csv_type == '5'
          @their_recipes_top10 = AboutService.fetch_their_recipe_views

          send_data @their_recipes_top10.to_csv,
                    filename: "Their_Recipes-Top-10-#{Date.today}.csv"
        else
          route to: 'about#analytics'
        end
      end
    end

    session_id = session.id
    GeneralPageService.record_views(session_id, 'About')
  end

  def show; end

  def contacts
    session_id = session.id
    GeneralPageService.record_views(session_id, 'Contacts')
  end

  def analytics
    @articles_view = AboutService.fetch_article_views

    @blog_view = AboutService.fetch_blog_views

    @recipes_view = AboutService.fetch_recipe_views

    @their_recipe_view = AboutService.fetch_their_recipe_views

    @general_page_views = AboutService.fetch_website_views

    session_id = session.id
    GeneralPageService.record_views(session_id, 'Analytics')
  end

  def health_and_safety
    session_id = session.id
    GeneralPageService.record_views(session_id, 'Health and Safety')
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

module AboutHelper
end

app/views/about/analytics.html.erb
<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>
    <h1>Analytics</h1>

    <div class='lineChart'>
      <span>Website Hits</span>
      <span class='csv'>
        <%= link_to 'CSV', about_index_path(format: 'csv', type: 1) %>
      </span>
      <%= line_chart @general_page_views.group_by_minute(:created_at).count,
        points: false %>
    </div>

    <div class='analyticsViewTable'>
      <div class='dbTable1'>
        <div class='analyticsBox'>
          <span>Blogs Top 10</span>
          <span class='csv'>
            <%= link_to 'CSV', about_index_path(format: 'csv', type: 2) %>
          </span>
          <table id="myTable">
            <thead>
              <tr>
                <th>Page Name</th>
                <th>Count</th>
                <th colspan="2"></th>
              </tr>
            </thead>
            <tbody>
            <% @blog_view.each do |page_name,count| %>
              <tr>
                <td><%= page_name %></td>
                <td><%= count %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

        <div class='analyticsBox'>
          <span>Recipes Top 10</span>
          <span class='csv'>
            <%= link_to 'CSV', about_index_path(format: 'csv', type: 3) %>
          </span>
          <table id="myTable">
            <thead>
              <tr>
                <th>Page Name</th>
                <th>Count</th>
                <th colspan="2"></th>
              </tr>
            </thead>
            <tbody>
            <% @recipes_view.each do |page_name,count| %>
              <tr>
                <td><%= page_name %></td>
                <td><%= count %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

        <div class='analyticsBox'>
          <span>Articles Top 10</span>
          <span class='csv'>
            <%= link_to 'CSV', about_index_path(format: 'csv', type: 4) %>
          </span>
          <table id="myTable">
            <thead>
              <tr>
                <th>Page Name</th>
                <th>Count</th>
                <th colspan="2"></th>
              </tr>
            </thead>
            <tbody>
            <% @articles_view.each do |page_name,count| %>
              <tr>
                <td><%= page_name %></td>
                <td><%= count %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

        <div class='analyticsBox'>
          <span>Their Recipes Top 10</span>
          <span class='csv'>
            <%= link_to 'CSV', about_index_path(format: 'csv', type: 5) %>
          </span>
          <table id="myTable">
            <thead>
              <tr>
                <th>Page Name</th>
                <th>Count</th>
                <th colspan="2"></th>
              </tr>
            </thead>
            <tbody>
            <% @their_recipe_view.first(10).each do |page_name,count| %>
              <tr>
                <td><%= page_name %></td>
                <td><%= count %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
  <%= render 'shared/footer' %>
</div>

app/views/about/contacts.html.erb
<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>
    <h1>Contacts</h1>

    <div class='contentText'>
      <p>
        All by myself
      </p>
      <p>
        Don't wanna be
      </p>
      <p>
        All by myself
      </p>
      <p>
        Anymore
      </p>

      <p>
        Yeahhh... so it's just me here by myself I'll direct you
        <%= link_to "here",
        "https://github.com/willllewellyn/Generic-Food-Blog",
        :target => "_blank" %>
        for any questions you might want to ask. 
      </p>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/about/health_and_safety.html.erb
<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>

    <h1>Health & Safety</h1>

    <div class='healthAndSafetyContent'>
      <div class='healthAndSafetyBox'>
        <span>Washing hands</span>
        <p>
          Our hands are one of the main ways that germs are spread. Harmful bacteria
          can be spread very easily from people's hands to food, work surfaces and
          equipment.
        </p>
        <p>
          It's always important to wash them thoroughly with soap and warm water
          before handling food, and especially after touching raw food, the bin,
          pets, and going to the toilet.
        </p>
        <p>
          <%= link_to "NHS",
          "https://www.nhs.uk/live-well/eat-well/how-to-prepare-and-cook-food-safely/#more-information",
          :target => "_blank" %>
        </p>
      </div>

      <div class='healthAndSafetyBox'>
        <span>Storing and preparing meat</span>
        <p>
          Raw meat, including poultry, can contain harmful bacteria that can
          spread easily to anything it touches, including food, worktops,
          tables, chopping boards, and knives.
        </p>
        <p>
          Take particular care to keep raw food separate from ready-to-eat foods
          such as bread, salad and fruit. These foods won't be cooked before you
          eat them, so any germs that get on to them won't be killed.
        </p>
        <p>
          <%= link_to "NHS",
          "https://www.nhs.uk/live-well/eat-well/how-to-prepare-and-cook-food-safely/#more-information",
          :target => "_blank" %>
        </p>
      </div>

      <div class='healthAndSafetyBox'>
        <span>Forklifts</span>
        <p>
          Hazard: Approximately 100 employees are fatally injured and approximately
          95,000 employees are injured every year while operating powered
          industrial trucks. Forklift turnover accounts for a significant number
          of these fatalities.
        </p>
        <p>
          Solutions:

          <ul>
            <li>
              Train and certify all operators to ensure that they operate
              forklifts
              safely.
            </li>
            <li>
              Do not allow any employee under 18 years old to operate a forklift.
              Properly maintain haulage equipment, including tires.
            </li>
            <li>
              Do not modify or make attachments that affect the capacity and safe
              operation of the forklift without written approval from the
              forklift's manufacturer.
            </li>
            <li>
              Examine forklift truck for defects before using.
            </li>
            <li>
              Follow safe operating procedures for picking up, moving, putting
              down and stacking loads.
            </li>
            <li>
              Drive safely--never exceed 5 mph and slow down in congested or
              slippery surface areas.
            </li>
            <li>
              Prohibit stunt driving and horseplay.
            </li>
            <li>
              Do not handle loads that are heavier than the capacity of the
              industrial truck.
            </li>
            <li>
              Remove unsafe or defective forklift trucks from service.
            </li>
            <li>
              Operators shall always wear seatbelts.
            </li>
            <li>
              Avoid traveling with elevated loads.
            </li>
            <li>
              Assure that rollover protective structure is in place.
            </li>
            <li>
              Make certain that the reverse signal alarm is operational and audible
              above the surrounding noise level.
            </li>
          </ul>
        </p>
        <p>
          <%= link_to "OSHA","https://www.osha.gov/Publications/OSHA3252/3252.html",
          :target => "_blank" %>
        </p>
      </div>

      <div class='healthAndSafetyBox'>
        <span>Common Sense</span>
        <p>
          We shouldn't have to say this stuff guys:
          <ul>
          <li>
            Please wear clothes while cooking
          </li>
          <li>
            Wash your hands after cutting peppers
          </li>
          <li>
            Cooking at a higher temperature doesn't mean it'll cook faster
          </li>
          <li>
            Don't juggle with knives... unless you're really good in which case
            go for it
          </li>
          <li>
            We don't recomend letting babies cut food, they're not very good at
            it, they just don't seem to be able to cut evenly
          </li>
          <li>
            Avoid cooking when under the unfluence of heavy cold medication
          </li>
          <li>
            No matter how much of a good idea it seems don't use knives as darts
          </li>
        </ul>
        </p>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/about/index.html.erb
<%= render 'shared/header' %>
<div class='container'>
  <div class='content'>
    <%= render 'shared/sidebar' %>
    <div class='contentText'>
      <div class='preamble'>
        <h1>About</h1>
      </div>
      <p>
        This website is being used to test a new Ruby gem that collects
        information about the website. No information is being collected
        about the visitors (you) so all your personal data and information is
        where you left it (providing you didn't click on any dodgy links before
        you got here). So if something doesn't work quite right this why, it is
        an experimental website being used to test code (don't worry you're
        safe). If something goes wrong here, all I can say is it's a
        experimental website and to report a bug, write a
        <%= link_to 'blog', blogs_path %>
         with the title "BUG: xxxx xxxx".
      </p>
      <p>
        The information about the website that is being gathered is:
      </p>
      <ul>
        <li> Which pages are being viewed </li>
        <li> What time the pages/links are visited </li>
      </ul>
      <p>
        Information not being gathered is:
      </p>
      <ul>
        <li> Information about you </li>
        <li> Your IP address </li>
        <li> Any personal information about you </li>
        <li> No cookies are used so no personal information about you or your
          browser is recorded </li>
      </ul>

      <div class='preamble'>
        <h1>Special Thanks</h1>
      </div>
      <p>
        I am no chief, so a big hand please to all the other websites that made
        this possible and in no particular order:
        <%= link_to "Imgur",
        "https://imgur.com/",
        :target => "_blank" %>,
        <%= link_to "Reddit",
        "https://www.reddit.com/",
        :target => "_blank" %>,
        <%= link_to "BBCGoodFood",
        "https://www.bbcgoodfood.com/",
        :target => "_blank" %>
        and last but not least
        <%= link_to "Food & Wine",
        "https://www.foodandwine.com/",
        :target => "_blank" %>
      </p>

      <div class='preamble'>
        <h1>Privacy Policy</h1>
      </div>
      <p>
        To reiterate again, we aren't collecting any data about you (we prefer
        to leave that to the NSA and GCHQ), only about the website it's self.
        We have one cookie that we use. It's a default Rails cookie about the
        session ID which is used so we can see if someone clicked on a
        seasonal recipe they also clicked on the drinks section. So to try and
        promote trust and transparency, all of the source code can be found
        <%= link_to "here",
        "https://github.com/willllewellyn/Generic-Food-Blog",
        :target => "_blank" %>
      </p>

      <div class='preamble'>
        <h1>Terms Of Use</h1>
      </div>
      <p>
        Please play nice, bit of a circle of trust going on here
      </p>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>